name: fastapi-zapatillas

services:
  fastapi-zapatillas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-zapatillas
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      zapatillas-db:
        condition: service_healthy
    environment:
      DB_USER: pablo
      DB_PASSWORD: 1234
      DB_HOST: zapatillas-db
      DB_PORT: 3306
      DB_NAME: zapatillas-db

  zapatillas-db:
    image: mysql
    container_name: zapatillas-mysql
    environment:
      MYSQL_ROOT_PASSWORD: pablo1234
      MYSQL_DATABASE: zapatillas-db
      MYSQL_USER: pablo
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

volumes:
  mysql_data:

